version: '3.8'

services:
  neo4j:
      image: neo4j:5.15.0-community # free community edition
      container_name: cao_neo4j
      ports:
        - "7474:7474" # HTTP (Browser UI)
        - "7687:7687" # Bolt (Database connections)
      environment:
        - NEO4J_AUTH=neo4j/16JANUARY2026
        - NEO4J_PLUGINS=["apoc"] # for graph utilities, cannot have extra space here
      volumes:
        - neo4j_data:/data
        - neo4j_logs:/logs

volumes: 
  neo4j_data:
  neo4j_logs: 